#!/bin/bash
# /eket-help - EKET 帮助

# 不使用 set -e，避免在可恢复错误处退出

# 动态路径配置 (v0.6.1)
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"
SCRIPTS_DIR="$PROJECT_ROOT/scripts"

echo "========================================"
echo "EKET Agent Framework - 帮助"
echo "========================================"
echo ""
echo "可用命令:"
echo ""
echo "  /eket-init         项目初始化向导（首次启动）"
echo "  /eket-start [-a]   启动实例（-a 启用自动模式）"
echo "  /eket-mode         切换模式（setup/execution）"
echo "  /eket-status       查看智能体状态和任务列表"
echo "  /eket-task [desc]  创建新任务或查看任务列表"
echo "  /eket-claim [id]   领取任务"
echo "  /eket-review [id]  请求对任务进行 Review"
echo "  /eket-help         显示此帮助信息"
echo ""
echo "工作流程:"
echo ""
echo "  任务设定模式（三仓库未初始化）:"
echo "    1. 在 inbox/human_input.md 中描述需求"
echo "    2. 协调智能体分析需求并创建任务"
echo "    3. 创建 Confluence 文档和 Jira 任务票"
echo ""
echo "  任务承接模式（三仓库已初始化）:"
echo "    1. 使用 /eket-start 启动实例"
echo "    2. 使用 /eket-status 查看推荐任务"
echo "    3. 使用 /eket-claim 领取任务"
echo "    4. 开发完成后使用 /eket-review 请求 Review"
echo ""
echo "文件位置:"
echo ""
echo "  inbox/human_input.md       - 需求输入"
echo "  inbox/human_feedback/      - Review 反馈"
echo "  jira/tickets/              - Jira 任务（优先）"
echo "  tasks/                     - 本地任务列表（回退）"
echo "  outbox/review_requests/    - Review 请求"
echo "  .eket/state/               - 状态文件"
echo "  .eket/state/agents/        - Agent Profile 配置"
echo "  skills/                    - Skills 定义"
echo ""
echo "脚本工具:"
echo ""
echo "  ./scripts/load-agent-profile.sh  <task-id>   - 加载 Agent Profile"
echo "  ./scripts/prioritize-tasks.sh [-a]           - 任务优先级排序"
echo "  ./scripts/recommend-tasks.sh                 - 推荐 Top 3 任务"
echo ""
echo "========================================"
