#!/bin/bash
# /eket-help - EKET 帮助

echo "========================================"
echo "EKET Agent Framework - 帮助"
echo "========================================"
echo ""
echo "可用命令:"
echo ""
echo "  /eket-status       查看智能体状态和任务列表"
echo "  /eket-task [desc]  创建新任务或查看任务列表"
echo "  /eket-review [id]  请求对任务进行 Review"
echo "  /eket-claim [id]   领取任务"
echo "  /eket-help         显示此帮助信息"
echo ""
echo "工作流程:"
echo ""
echo "  1. 在 inbox/human_input.md 中描述需求"
echo "  2. 使用 /eket-status 查看状态"
echo "  3. 使用 /eket-task 创建任务"
echo "  4. 使用 /eket-claim 领取任务"
echo "  5. 完成任务后使用 /eket-review 请求 Review"
echo ""
echo "文件位置:"
echo ""
echo "  inbox/human_input.md       - 需求输入"
echo "  inbox/human_feedback/      - Review 反馈"
echo "  tasks/                     - 任务列表"
echo "  outbox/review_requests/    - Review 请求"
echo "  .eket/state/               - 状态文件"
echo ""
echo "========================================"
