/**
 * Context Alert System for Master notification
 *
 * Triggers when token count approaches limits (150K+)
 * Creates alert files in .eket/inbox/ for Master polling
 * Deduplicates alerts per task to avoid spam
 */

import { writeFileSync, readFileSync, existsSync, mkdirSync } from 'fs';
import { join, dirname } from 'path';

export interface AlertContext {
  taskId: string;
  tokens: number;
  turnCount?: number;
  timestamp: string;
}

export interface AlertRecord {
  taskId: string;
  alertedAt: string;
}

export class ContextAlert {
  private readonly ALERT_THRESHOLD = 150000;
  private readonly INBOX_DIR = '.eket/inbox';
  private readonly STATE_FILE = '.eket/state/alerted-tasks.json';

  /**
   * Check if alert should be triggered and send if needed
   * @param context - Current context information
   * @returns true if alert was sent, false if skipped (below threshold or duplicate)
   */
  async alertMaster(context: AlertContext): Promise<boolean> {
    // Skip if below threshold
    if (context.tokens < this.ALERT_THRESHOLD) {
      return false;
    }

    // Skip if already alerted for this task
    if (this.hasBeenAlerted(context.taskId)) {
      return false;
    }

    // Create alert file
    this.createAlertFile(context);

    // Record alert to prevent duplicates
    this.recordAlert(context.taskId);

    return true;
  }

  /**
   * Check if task has been alerted before
   */
  private hasBeenAlerted(taskId: string): boolean {
    if (!existsSync(this.STATE_FILE)) {
      return false;
    }

    try {
      const content = readFileSync(this.STATE_FILE, 'utf-8');
      const records: AlertRecord[] = JSON.parse(content);
      return records.some(r => r.taskId === taskId);
    } catch {
      // Corrupted state file, treat as no alerts
      return false;
    }
  }

  /**
   * Record alert to prevent future duplicates
   */
  private recordAlert(taskId: string): void {
    let records: AlertRecord[] = [];

    // Load existing records
    if (existsSync(this.STATE_FILE)) {
      try {
        const content = readFileSync(this.STATE_FILE, 'utf-8');
        records = JSON.parse(content);
      } catch {
        // Corrupted file, start fresh
        records = [];
      }
    }

    // Add new record
    records.push({
      taskId,
      alertedAt: new Date().toISOString()
    });

    // Ensure directory exists
    const stateDir = dirname(this.STATE_FILE);
    if (!existsSync(stateDir)) {
      mkdirSync(stateDir, { recursive: true });
    }

    // Write back
    writeFileSync(this.STATE_FILE, JSON.stringify(records, null, 2), 'utf-8');
  }

  /**
   * Create alert markdown file in inbox
   */
  private createAlertFile(context: AlertContext): void {
    const filename = `context-risk-${context.taskId}.md`;
    const filepath = join(this.INBOX_DIR, filename);

    // Ensure directory exists
    if (!existsSync(this.INBOX_DIR)) {
      mkdirSync(this.INBOX_DIR, { recursive: true });
    }

    const content = this.formatAlert(context);
    writeFileSync(filepath, content, 'utf-8');
  }

  /**
   * Format alert content as markdown
   */
  private formatAlert(context: AlertContext): string {
    const { taskId, tokens, turnCount, timestamp } = context;

    return `# Context Risk Alert: ${taskId}

**Tokens**: ${tokens.toLocaleString()}
**Turn Count**: ${turnCount ?? 'N/A'}
**Timestamp**: ${timestamp}

## Recommendation

Context approaching token limit (${this.ALERT_THRESHOLD.toLocaleString()}+).

**Suggested Actions**:
1. **Compact memory** - Run context compression on old tickets
2. **Archive old tickets** - Move completed tickets to archive/
3. **Split task** - If multi-stage, break into subtasks
4. **Review active context** - Check .eket/ACTIVE_CONTEXT.md for bloat

**Automation**:
\`\`\`bash
# Quick compaction
node dist/index.js memory:compact

# Archive completed tickets
node dist/index.js ticket:archive --status=done

# Check context breakdown
node dist/index.js context:analyze
\`\`\`

---

**Generated by**: ContextAlert v1.0.0
**Alert Threshold**: ${this.ALERT_THRESHOLD.toLocaleString()} tokens
`;
  }

  /**
   * Clear alert history (for testing or reset)
   * @param taskId - Optional specific task to clear, or all if omitted
   */
  clearAlertHistory(taskId?: string): void {
    if (!existsSync(this.STATE_FILE)) {
      return;
    }

    if (!taskId) {
      // Clear all
      writeFileSync(this.STATE_FILE, '[]', 'utf-8');
      return;
    }

    // Clear specific task
    try {
      const content = readFileSync(this.STATE_FILE, 'utf-8');
      const records: AlertRecord[] = JSON.parse(content);
      const filtered = records.filter(r => r.taskId !== taskId);
      writeFileSync(this.STATE_FILE, JSON.stringify(filtered, null, 2), 'utf-8');
    } catch {
      // If can't read, just clear all
      writeFileSync(this.STATE_FILE, '[]', 'utf-8');
    }
  }
}
