/**
 * EKET Framework - Skill Auto-Generator (TASK-043)
 *
 * 从 ticket 复盘描述自动提炼 Skill 元数据并生成 .ts 文件。
 * 使用静态模板（非 LLM）确保 TypeScript 编译通过。
 */

import { existsSync } from 'fs';
import { writeFile, mkdir } from 'fs/promises';
import { join } from 'path';

// ─── Types ────────────────────────────────────────────────────────────────────

export interface SkillExtractInput {
  ticket: string;   // e.g. "TASK-042"
  summary: string;  // 解法描述
  steps?: string;   // 逗号分隔的步骤（可选）
  category?: string; // 可选，默认推断
}

export interface AutoSkill {
  id: string;
  name: string;
  category: string;
  description: string;
  trigger: string[];
  steps: string[];
  relatedTicket: string;
  createdAt: string;
}

// ─── Helpers ──────────────────────────────────────────────────────────────────

export function inferCategory(summary: string): string {
  const lower = summary.toLowerCase();
  if (lower.includes('zod') || lower.includes('schema') || lower.includes('validate')) {return 'requirements';}
  if (lower.includes('test') || lower.includes('hook') || lower.includes('assert')) {return 'testing';}
  if (lower.includes('ci') || lower.includes('deploy') || lower.includes('infra') || lower.includes('docker')) {return 'devops';}
  if (lower.includes('design') || lower.includes('architect') || lower.includes('interface')) {return 'design';}
  if (lower.includes('doc') || lower.includes('readme')) {return 'documentation';}
  return 'development';
}

export function summaryToId(summary: string): string {
  return summary
    .toLowerCase()
    .replace(/[^a-z0-9\s]/g, '')
    .trim()
    .split(/\s+/)
    .slice(0, 5)
    .join('-');
}

// ─── Generator ────────────────────────────────────────────────────────────────

export async function generateSkillFile(
  repoRoot: string,
  input: SkillExtractInput,
): Promise<{ filePath: string; skill: AutoSkill }> {
  const category = input.category ?? inferCategory(input.summary);
  const id = summaryToId(input.summary);
  const varName = id.replace(/-([a-z])/g, (_: string, c: string) => c.toUpperCase()) + 'Skill';
  const now = new Date().toISOString().split('T')[0] ?? new Date().toISOString();
  const steps = input.steps
    ? input.steps.split(',').map((s, i) => `${i + 1}. ${s.trim()}`)
    : [`1. ${input.summary}`];
  const trigger = input.summary.toLowerCase().replace(/[^a-z0-9\s]/g, '').split(/\s+/).slice(0, 4);

  const skill: AutoSkill = {
    id,
    name: input.summary.slice(0, 60),
    category,
    description: input.summary,
    trigger,
    steps,
    relatedTicket: input.ticket,
    createdAt: now,
  };

  const skillJson = JSON.stringify(skill, null, 2)
    .replace(/"([a-zA-Z_][a-zA-Z0-9_]*)"\s*:/g, '$1:'); // unquote keys

  const code = `// AUTO-GENERATED by skill:extract — ${input.ticket} — ${now}
// DO NOT EDIT manually; regenerate with skill:extract

import type { AutoSkill } from '../../core/skill-generator.js';

export const ${varName}: AutoSkill = ${skillJson};

export default ${varName};
`;

  const dir = join(repoRoot, 'node', 'src', 'skills', category);
  if (!existsSync(dir)) {await mkdir(dir, { recursive: true });}
  const filePath = join(dir, `auto-${id}.ts`);
  await writeFile(filePath, code, 'utf-8');

  return { filePath, skill };
}
