/**
 * Slaver Context Monitor
 * TASK-608: Detect context overflow risk and report to Master
 *
 * Feature: Slaver auto-reports when context > 120k tokens
 * - Generates alert file to .eket/inbox/
 * - Includes ticket summary, token stats, split suggestion
 */

import * as fs from 'fs';
import * as path from 'path';
import { contextTracker } from './context-tracker.js';

export interface SplitSuggestion {
  taskId: string;
  currentTokens: number;
  riskLevel: 'low' | 'high';
  timestamp: string;
}

/**
 * Check if Slaver should report context risk to Master
 * Called periodically during task execution
 */
export function shouldReportRisk(sessionId: string): boolean {
  const risk = contextTracker.checkRisk(sessionId);
  return risk === 'high'; // Only report when > 120k
}

/**
 * Generate Master alert file for task split suggestion
 *
 * @param projectRoot - Project root path
 * @param taskId - Current ticket ID
 * @param sessionId - Session ID for token tracking
 * @returns Path to created alert file
 */
export async function reportContextRisk(
  projectRoot: string,
  taskId: string,
  sessionId: string
): Promise<string> {
  const tokens = contextTracker.getSessionTokens(sessionId);
  const risk = contextTracker.checkRisk(sessionId);
  const timestamp = new Date().toISOString().replace(/[:.]/g, '-');

  const alertPath = path.join(
    projectRoot,
    '.eket',
    'inbox',
    `context-risk-${taskId}-${timestamp}.md`
  );

  const content = `# Context Overflow Risk Alert

**Generated**: ${new Date().toISOString()}
**Task ID**: ${taskId}
**Current Tokens**: ${tokens.toLocaleString()} / 200,000
**Risk Level**: ${risk.toUpperCase()}

## Issue
Slaver detected context approaching 200k limit during task execution.

## Current Ticket Summary
<!-- TODO: TASK-608 Phase 2.3 - Auto-extract from ticket file -->
Task: ${taskId}
Status: in-progress
Estimated completion: Unknown

## Analysis
- **Token usage**: ${((tokens / 200000) * 100).toFixed(1)}% of limit
- **Threshold**: 120k exceeded
- **Recommendation**: Split into sub-tasks

## Suggested Split Strategy
<!-- TODO: TASK-608 Phase 2.4 - Smart analysis (future enhancement) -->
1. Review ticket acceptance criteria
2. Identify natural breakpoints (phases/modules)
3. Split into 2-3 sub-tasks via \`eket task:split ${taskId}\`

## Master Actions Required
\`\`\`bash
# Review ticket and decide split strategy
cat jira/tickets/${taskId}.md

# Option 1: Split into sub-tasks (recommended)
eket task:split ${taskId}

# Option 2: Force compact and continue (risky)
# Slaver will auto-compact, but may hit limit again
\`\`\`

---
*Auto-generated by TASK-608 Slaver Context Monitor*
`;

  // Ensure inbox directory exists
  fs.mkdirSync(path.dirname(alertPath), { recursive: true });
  fs.writeFileSync(alertPath, content, 'utf-8');

  console.log(`📋 Context risk alert created: ${alertPath}`);
  return alertPath;
}

/**
 * Periodic check during Slaver task execution
 * Call this after major operations (tool output tracking)
 *
 * @param projectRoot - Project root path
 * @param sessionId - Session ID for tracking
 * @returns Alert path if reported, null if no action needed
 */
export async function checkAndReportIfNeeded(
  projectRoot: string,
  sessionId: string
): Promise<string | null> {
  if (!shouldReportRisk(sessionId)) {
    return null;
  }

  // Read task ID from agent profile
  const taskId = readTaskIdFromProfile(projectRoot);
  if (taskId === 'unknown') {
    console.warn('⚠️  Cannot report context risk: task ID unknown');
    return null;
  }

  // Generate alert
  return await reportContextRisk(projectRoot, taskId, sessionId);
}

/**
 * Helper: Read task ID from agent_profile.yml
 */
function readTaskIdFromProfile(projectRoot: string): string {
  try {
    const profilePath = path.join(projectRoot, '.eket', 'state', 'agent_profile.yml');
    const content = fs.readFileSync(profilePath, 'utf-8');
    const match = content.match(/^current_ticket:\s*(.+)$/m);
    return match ? match[1].trim() : 'unknown';
  } catch {
    return 'unknown';
  }
}
