/**
 * Compact Trigger Watcher - TASK-AUTO-02
 *
 * Monitors .eket/triggers/compact.trigger and creates urgent alerts
 * when context reaches critical levels.
 *
 * AC-1: Detect trigger file changes within 1s
 * AC-2: Create urgent alert file
 * AC-3: Trigger macOS notification (optional)
 */

import { watch } from 'node:fs/promises';
import { readFile, writeFile } from 'node:fs/promises';
import { execFile } from 'node:child_process';
import { promisify } from 'node:util';
import { join } from 'node:path';

const execFileAsync = promisify(execFile);

export interface TriggerData {
  type: string;
  tokens: number;
  timestamp: string;
}

export interface WatcherOptions {
  triggerPath?: string;
  inboxPath?: string;
  enableNotifications?: boolean;
}

/**
 * Parse trigger file content
 * Format: AUTO_COMPACT_REQUEST|125000|2026-05-14T18:30:00Z
 */
export function parseTriggerData(content: string): TriggerData | null {
  const parts = content.trim().split('|');
  if (parts.length !== 3 || parts[0] !== 'AUTO_COMPACT_REQUEST') {
    return null;
  }

  const tokens = parseInt(parts[1], 10);
  if (isNaN(tokens)) {
    return null;
  }

  return {
    type: parts[0],
    tokens,
    timestamp: parts[2],
  };
}

/**
 * Create urgent alert file in inbox
 * AC-2: Creates [URGENT] AUTO-COMPACT-*.md
 */
export async function createUrgentAlert(
  data: TriggerData,
  inboxPath: string
): Promise<string> {
  const alertFile = join(inboxPath, `[URGENT] AUTO-COMPACT-${Date.now()}.md`);

  const content = `# 🔴 URGENT: Auto-Compact Required

**Estimated Tokens**: ${data.tokens.toLocaleString()}
**Triggered**: ${data.timestamp}
**Alert Created**: ${new Date().toISOString()}

---

## Immediate Action Required

Run this command NOW to prevent 400 error:

\`\`\`bash
/compact
\`\`\`

## After Running /compact

1. Verify context size reduced
2. Delete this alert:
   \`\`\`bash
   rm "${alertFile}"
   \`\`\`
3. Delete trigger file:
   \`\`\`bash
   rm .eket/triggers/compact.trigger
   \`\`\`

---

**Auto-generated by**: compact-trigger-watcher (TASK-AUTO-02)
**Session**: Layer 1 Defense - Auto-Compact Trigger
`;

  await writeFile(alertFile, content, 'utf-8');
  return alertFile;
}

/**
 * Send macOS notification (optional, graceful fail)
 * AC-3: System notification on macOS
 */
export async function sendMacNotification(tokens: number): Promise<boolean> {
  if (process.platform !== 'darwin') {
    return false; // Not macOS
  }

  try {
    const message = `Context: ${tokens.toLocaleString()} tokens - Run /compact NOW`;
    await execFileAsync('osascript', [
      '-e',
      `display notification "${message}" with title "EKET Critical Alert"`,
    ]);
    return true;
  } catch {
    return false; // Notification failed, graceful skip
  }
}

/**
 * Main watcher loop
 * AC-1: Monitors trigger file with 1s responsiveness
 */
export async function watchCompactTrigger(
  options: WatcherOptions = {}
): Promise<void> {
  const triggerPath =
    options.triggerPath ?? '.eket/triggers/compact.trigger';
  const inboxPath = options.inboxPath ?? '.eket/inbox';
  const enableNotifications = options.enableNotifications ?? true;

  console.log(`[Compact Watcher] Started monitoring: ${triggerPath}`);

  try {
    const watcher = watch(triggerPath, { persistent: true });

    for await (const event of watcher) {
      if (event.eventType === 'change' || event.eventType === 'rename') {
        console.log(
          `[Compact Watcher] Detected ${event.eventType} at ${new Date().toISOString()}`
        );

        // Read and parse trigger file
        let content: string;
        try {
          content = await readFile(triggerPath, 'utf-8');
        } catch (err) {
          console.warn('[Compact Watcher] Trigger file removed or inaccessible');
          continue;
        }

        const data = parseTriggerData(content);
        if (!data) {
          console.warn('[Compact Watcher] Invalid trigger data:', content);
          continue;
        }

        // AC-2: Create urgent alert
        const alertFile = await createUrgentAlert(data, inboxPath);
        console.error(`🔴 AUTO-COMPACT ALERT: ${data.tokens} tokens`);
        console.error(`📝 Alert created: ${alertFile}`);

        // AC-3: Optional notification
        if (enableNotifications) {
          const notified = await sendMacNotification(data.tokens);
          if (notified) {
            console.log('[Compact Watcher] macOS notification sent');
          }
        }
      }
    }
  } catch (err) {
    if ((err as NodeJS.ErrnoException).code === 'ENOENT') {
      console.log(
        '[Compact Watcher] Trigger file does not exist, waiting for creation...'
      );
      // In production, you'd use fs.watch on parent directory
      // For now, exit gracefully
      return;
    }
    throw err;
  }
}

/**
 * Start watcher in background (non-blocking)
 */
export function startWatcher(options?: WatcherOptions): void {
  watchCompactTrigger(options).catch((err) => {
    console.error('[Compact Watcher] Fatal error:', err);
    process.exit(1);
  });
}
