/**
 * EKET Framework - Task Verification Tests
 *
 * Tests for `eket task:verify` command functionality.
 *
 * Covers:
 * - Progress.md parsing
 * - File existence verification
 * - Git commit verification
 * - Timestamp monotonicity
 * - Fake progress detection
 */

import fs from 'fs/promises';
import path from 'path';
import { execFile } from 'child_process';
import { promisify } from 'util';
import { parseProgressMarkdown } from '../../src/utils/progress-parser.js';
import { TaskPhase } from '../../src/types/progress-tracker.js';

const execFileAsync = promisify(execFile);

describe('Progress Parser', () => {
  it('should parse valid progress.md', () => {
    const content = `# Task Progress: TASK-123

**Last Update**: 2026-05-14T10:00:00Z
**Slaver**: slaver-008
**Current Phase**: \`implementation\`

## Completed
- [x] analysis (05/14/2026, 10:00:00 AM)
  - artifact: analysis-report.md
  - commit: abc123def

- [x] AC-1 (05/14/2026, 11:00:00 AM)
  - files: src/auth.ts, src/db.ts
  - test: ✅
  - commit: def456ghi

## Next Steps
- [ ] Implement AC-2
- [ ] Write integration tests

## Blockers
- None

---
*Generated by ProgressTracker*
`;

    const result = parseProgressMarkdown(content, 'TASK-123');

    expect(result.success).toBe(true);
    expect(result.data).toBeDefined();
    expect(result.data!.taskId).toBe('TASK-123');
    expect(result.data!.slaverId).toBe('slaver-008');
    expect(result.data!.currentPhase).toBe('implementation');
    expect(result.data!.checkpoints.length).toBeGreaterThanOrEqual(2);

    // Check first checkpoint
    const firstCheckpoint = result.data!.checkpoints[0];
    expect(firstCheckpoint.phase).toBe('analysis');
    expect(firstCheckpoint.metadata.artifact).toBe('analysis-report.md');
    expect(firstCheckpoint.metadata.commit).toBe('abc123def');

    // Check second checkpoint
    const secondCheckpoint = result.data!.checkpoints[1];
    expect(secondCheckpoint.phase).toBe('AC-1');
    expect(secondCheckpoint.metadata.files).toEqual(['src/auth.ts', 'src/db.ts']);
    expect(secondCheckpoint.metadata.tests?.passed).toBe(true);
    expect(secondCheckpoint.metadata.commit).toBe('def456ghi');

    // Check next steps
    expect(result.data!.nextSteps.length).toBe(2);
    expect(result.data!.nextSteps[0]).toContain('Implement AC-2');
  });

  it('should handle missing Slaver field', () => {
    const content = `# Task Progress: TASK-456

**Last Update**: 2026-05-14T10:00:00Z
**Current Phase**: \`analysis\`

## Completed
- [x] analysis (05/14/2026, 10:00:00 AM)
`;

    const result = parseProgressMarkdown(content, 'TASK-456');

    expect(result.success).toBe(false);
    expect(result.error?.message).toContain('Slaver');
  });

  it('should parse completed phases correctly', () => {
    const content = `# Task Progress: TASK-789

**Last Update**: 2026-05-14T10:00:00Z
**Slaver**: slaver-007
**Current Phase**: \`testing\`

## Completed
- [x] analysis (05/14/2026, 09:00:00 AM)
- [x] design (05/14/2026, 09:30:00 AM)
- [x] implementation (05/14/2026, 10:30:00 AM)

## Blockers
- None
`;

    const result = parseProgressMarkdown(content, 'TASK-789');

    expect(result.success).toBe(true);
    expect(result.data!.completedPhases.has('analysis')).toBe(true);
    expect(result.data!.completedPhases.has('design')).toBe(true);
    expect(result.data!.completedPhases.has('implementation')).toBe(true);
  });
});

describe('Verification Logic', () => {
  const testDir = path.join(process.cwd(), '.test-temp/verify-tests');

  beforeAll(async () => {
    // Create test directory
    await fs.mkdir(testDir, { recursive: true });
    process.chdir(testDir);

    // Initialize git repo
    await execFileAsync('git', ['init']);
    await execFileAsync('git', ['config', 'user.name', 'Test User']);
    await execFileAsync('git', ['config', 'user.email', 'test@example.com']);
  });

  afterAll(async () => {
    // Cleanup
    process.chdir(path.join(process.cwd(), '../..'));
    await fs.rm(testDir, { recursive: true, force: true });
  });

  it('should verify file existence', async () => {
    // Create test files
    await fs.mkdir(path.join(testDir, 'src'), { recursive: true });
    await fs.writeFile(path.join(testDir, 'src/auth.ts'), '// test file');
    await fs.writeFile(path.join(testDir, 'src/db.ts'), '// test file');

    // Verify files exist
    const files = ['src/auth.ts', 'src/db.ts'];
    const missing: string[] = [];

    for (const file of files) {
      const filePath = path.join(testDir, file);
      try {
        await fs.access(filePath);
      } catch {
        missing.push(file);
      }
    }

    expect(missing.length).toBe(0);
  });

  it('should detect missing files', async () => {
    const files = ['src/auth.ts', 'src/db.ts', 'src/missing.ts'];
    const missing: string[] = [];

    for (const file of files) {
      const filePath = path.join(testDir, file);
      try {
        await fs.access(filePath);
      } catch {
        missing.push(file);
      }
    }

    expect(missing.length).toBe(1);
    expect(missing[0]).toBe('src/missing.ts');
  });

  it('should verify git commit exists', async () => {
    // Create a commit
    await fs.writeFile(path.join(testDir, 'test.txt'), 'test content');
    await execFileAsync('git', ['add', 'test.txt']);
    await execFileAsync('git', ['commit', '-m', 'test commit']);

    // Get commit hash
    const { stdout } = await execFileAsync('git', ['rev-parse', 'HEAD']);
    const commit = stdout.trim();

    // Verify commit exists
    let commitExists = false;
    try {
      await execFileAsync('git', ['show', '--quiet', commit]);
      commitExists = true;
    } catch {
      commitExists = false;
    }

    expect(commitExists).toBe(true);
  });

  it('should detect fake commit hash', async () => {
    const fakeCommit = 'abc123def456ghi789';

    let commitExists = false;
    try {
      await execFileAsync('git', ['show', '--quiet', fakeCommit]);
      commitExists = true;
    } catch {
      commitExists = false;
    }

    expect(commitExists).toBe(false);
  });

  it('should verify timestamp monotonicity', () => {
    const checkpoints = [
      { timestamp: '2026-05-14T09:00:00Z', phase: 'analysis', metadata: {} },
      { timestamp: '2026-05-14T09:30:00Z', phase: 'design', metadata: {} },
      { timestamp: '2026-05-14T10:00:00Z', phase: 'implementation', metadata: {} },
    ];

    let isMonotonic = true;
    let previousTime = 0;

    for (const cp of checkpoints) {
      const currentTime = new Date(cp.timestamp).getTime();
      if (currentTime < previousTime) {
        isMonotonic = false;
        break;
      }
      previousTime = currentTime;
    }

    expect(isMonotonic).toBe(true);
  });

  it('should detect timestamp violation', () => {
    const checkpoints = [
      { timestamp: '2026-05-14T09:00:00Z', phase: 'analysis', metadata: {} },
      { timestamp: '2026-05-14T10:00:00Z', phase: 'design', metadata: {} },
      { timestamp: '2026-05-14T09:30:00Z', phase: 'implementation', metadata: {} }, // Out of order
    ];

    let isMonotonic = true;
    let previousTime = 0;

    for (const cp of checkpoints) {
      const currentTime = new Date(cp.timestamp).getTime();
      if (currentTime < previousTime) {
        isMonotonic = false;
        break;
      }
      previousTime = currentTime;
    }

    expect(isMonotonic).toBe(false);
  });
});

describe('Integration Test', () => {
  const testDir = path.join(process.cwd(), '.test-temp/verify-integration');

  beforeAll(async () => {
    await fs.mkdir(testDir, { recursive: true });
    await fs.mkdir(path.join(testDir, 'jira/tickets/TASK-TEST-001'), { recursive: true });
  });

  afterAll(async () => {
    await fs.rm(testDir, { recursive: true, force: true });
  });

  it('should verify complete valid progress.md', async () => {
    const progressContent = `# Task Progress: TASK-TEST-001

**Last Update**: 2026-05-14T10:30:00Z
**Slaver**: slaver-008
**Current Phase**: \`implementation\`

## Completed
- [x] analysis (05/14/2026, 09:00:00 AM)
  - artifact: analysis-report.md

- [x] AC-1 (05/14/2026, 10:00:00 AM)
  - files: src/test.ts
  - test: ✅

## Next Steps
- [ ] Complete AC-2

## Blockers
- None

---
*Generated by ProgressTracker*
`;

    // Write progress.md
    const progressPath = path.join(testDir, 'jira/tickets/TASK-TEST-001/progress.md');
    await fs.writeFile(progressPath, progressContent);

    // Create test file
    await fs.mkdir(path.join(testDir, 'src'), { recursive: true });
    await fs.writeFile(path.join(testDir, 'src/test.ts'), '// test');

    // Parse
    const result = parseProgressMarkdown(progressContent, 'TASK-TEST-001');

    expect(result.success).toBe(true);
    expect(result.data!.checkpoints.length).toBeGreaterThanOrEqual(2);
  });
});
