#!/bin/bash
# supervisor.sh - External Supervisor for Master/Slaver Heartbeat Monitoring
#
# Purpose:
#   Monitor Master and Slaver heartbeat files and generate alerts when timeout occurs.
#   This script runs independently from Claude/Node.js processes.
#
# Usage:
#   bash scripts/supervisor.sh
#   # Or run in background:
#   nohup bash scripts/supervisor.sh >> .eket/logs/supervisor.log 2>&1 &
#
# Environment:
#   EKET_ROOT: Project root directory (auto-detected if running from scripts/)
#   SUPERVISOR_INTERVAL: Check interval in seconds (default: 60)

set -euo pipefail

# ==============================================================================
# Configuration
# ==============================================================================

# Auto-detect project root
if [[ -z "${EKET_ROOT:-}" ]]; then
  SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
  EKET_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
fi

# Thresholds (seconds)
MASTER_TIMEOUT=300   # 5 minutes
SLAVER_TIMEOUT=650   # ~11 minutes

# Check interval
INTERVAL="${SUPERVISOR_INTERVAL:-60}"

# Paths
STATE_DIR="$EKET_ROOT/.eket/state"
INBOX_DIR="$EKET_ROOT/.eket/inbox"
MASTER_HB="$STATE_DIR/master-heartbeat"
RECOVERY_QUEUE="$STATE_DIR/recovery-queue.txt"
LOG_FILE="$EKET_ROOT/.eket/logs/supervisor.log"

# ==============================================================================
# Platform Detection
# ==============================================================================

# Detect OS and set appropriate stat command
if [[ "$OSTYPE" == "darwin"* ]]; then
  # macOS
  get_mtime() {
    stat -f %m "$1" 2>/dev/null || echo 0
  }
elif [[ "$OSTYPE" == "linux-gnu"* ]]; then
  # Linux
  get_mtime() {
    stat -c %Y "$1" 2>/dev/null || echo 0
  }
else
  echo "Error: Unsupported OS: $OSTYPE" >&2
  exit 1
fi

# ==============================================================================
# Logging
# ==============================================================================

log() {
  local level="$1"
  shift
  echo "[$(date -Iseconds)] [$level] $*" | tee -a "$LOG_FILE"
}

# ==============================================================================
# Alert Generation
# ==============================================================================

# Generate Master critical alert
generate_master_alert() {
  local now="$1"
  local last_heartbeat="$2"
  local alert_file="$INBOX_DIR/[CRITICAL]-MASTER-$now.md"

  cat > "$alert_file" <<EOF
# Master Heartbeat Timeout

**Time**: $(date -Iseconds)
**Last Heartbeat**: $(date -Iseconds -r "$last_heartbeat" 2>/dev/null || echo "Unknown")
**Status**: Master process appears dead (>$MASTER_TIMEOUT s timeout)

---

## Symptom

Master heartbeat file has not been updated for more than $MASTER_TIMEOUT seconds.

## Impact

- No new tasks will be analyzed or assigned
- PR reviews may be blocked
- Slaver progress reports will not be processed

## Action Required

1. Check Master process logs: \`.eket/logs/master.log\`
2. Check if Master Claude session is still running
3. Restart Master if needed: \`/eket-start -r master\`
4. Check \`shared/message_queue/inbox/\` for pending messages

---

**Alert ID**: MASTER-$now
**Generated by**: supervisor.sh
EOF

  log "CRITICAL" "Master alert generated: $alert_file"
}

# Add Slaver to recovery queue
add_to_recovery_queue() {
  local slaver_id="$1"
  local now="$2"

  # Avoid duplicates (check last line)
  if [[ -f "$RECOVERY_QUEUE" ]]; then
    last_entry=$(tail -1 "$RECOVERY_QUEUE" 2>/dev/null || echo "")
    if [[ "$last_entry" == "$slaver_id|"* ]]; then
      log "WARN" "Slaver $slaver_id already in recovery queue, skipping"
      return
    fi
  fi

  echo "$slaver_id|$now" >> "$RECOVERY_QUEUE"
  log "WARN" "Slaver $slaver_id added to recovery queue (timeout: $SLAVER_TIMEOUT s)"
}

# ==============================================================================
# Monitoring Functions
# ==============================================================================

# Monitor Master heartbeat
check_master() {
  local now="$1"

  if [[ ! -f "$MASTER_HB" ]]; then
    log "WARN" "Master heartbeat file not found: $MASTER_HB"
    return
  fi

  local master_last=$(get_mtime "$MASTER_HB")
  local elapsed=$((now - master_last))

  if [[ $elapsed -gt $MASTER_TIMEOUT ]]; then
    log "ERROR" "Master heartbeat timeout detected: ${elapsed}s > ${MASTER_TIMEOUT}s"
    generate_master_alert "$now" "$master_last"
  else
    log "DEBUG" "Master heartbeat OK (${elapsed}s ago)"
  fi
}

# Monitor Slaver heartbeats
check_slavers() {
  local now="$1"

  # Find all slaver heartbeat files
  local slaver_count=0
  local timeout_count=0

  for hb_file in "$STATE_DIR"/slaver-*-heartbeat; do
    # Skip if glob didn't match any files
    [[ -f "$hb_file" ]] || continue

    slaver_count=$((slaver_count + 1))

    # Extract Slaver ID from filename
    local filename=$(basename "$hb_file")
    local slaver_id="${filename#slaver-}"
    slaver_id="${slaver_id%-heartbeat}"

    local slaver_last=$(get_mtime "$hb_file")
    local elapsed=$((now - slaver_last))

    if [[ $elapsed -gt $SLAVER_TIMEOUT ]]; then
      log "WARN" "Slaver $slaver_id heartbeat timeout: ${elapsed}s > ${SLAVER_TIMEOUT}s"
      add_to_recovery_queue "$slaver_id" "$now"
      timeout_count=$((timeout_count + 1))
    else
      log "DEBUG" "Slaver $slaver_id heartbeat OK (${elapsed}s ago)"
    fi
  done

  if [[ $slaver_count -eq 0 ]]; then
    log "INFO" "No active Slavers detected"
  else
    log "INFO" "Monitored $slaver_count Slaver(s), $timeout_count timeout(s)"
  fi
}

# ==============================================================================
# Main Loop
# ==============================================================================

# Signal handlers
cleanup() {
  log "INFO" "Supervisor stopped (signal received)"
  exit 0
}

trap cleanup SIGINT SIGTERM

# Initialize
log "INFO" "Supervisor started (PID: $$)"
log "INFO" "Project root: $EKET_ROOT"
log "INFO" "Master timeout: ${MASTER_TIMEOUT}s, Slaver timeout: ${SLAVER_TIMEOUT}s"
log "INFO" "Check interval: ${INTERVAL}s"

# Create necessary directories
mkdir -p "$STATE_DIR" "$INBOX_DIR" "$(dirname "$LOG_FILE")"

# Main loop
while true; do
  NOW=$(date +%s)

  log "INFO" "--- Heartbeat check cycle start ---"

  # Check Master
  check_master "$NOW"

  # Check Slavers
  check_slavers "$NOW"

  log "INFO" "--- Heartbeat check cycle end ---"

  # Sleep
  sleep "$INTERVAL"
done
