#!/usr/bin/env bash
# sync-ignore-files.sh — 规则驱动的 ignore 文件动态生成器
#
# 用法：
#   bash scripts/sync-ignore-files.sh                    # 检测语言 + 生成所有 ignore 文件
#   bash scripts/sync-ignore-files.sh --check            # 检查是否需要更新（exit 1 if dirty）
#   bash scripts/sync-ignore-files.sh --lang rust,node   # 仅生成指定语言规则
#
# 原理：
#   1. 扫描项目检测语言（Cargo.toml → rust, package.json → node, etc.）
#   2. 从 scripts/ignore-rules/*.rules 读取规则模板
#   3. 合并生成 .gitignore / .dockerignore / .claudeignore

set -euo pipefail

PROJECT_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
RULES_DIR="$PROJECT_ROOT/scripts/ignore-rules"

# ─── 语言检测 ─────────────────────────────────────────────────────────────────

detect_languages() {
  local langs=()

  [[ -f "$PROJECT_ROOT/rust/Cargo.toml" ]] && langs+=("rust")
  [[ -f "$PROJECT_ROOT/node/package.json" ]] && langs+=("node")
  [[ -f "$PROJECT_ROOT/package.json" ]] && langs+=("node")

  # Python: setup.py / requirements.txt / Pipfile / pyproject.toml
  if find "$PROJECT_ROOT" -maxdepth 3 -type f \( -name "setup.py" -o -name "requirements.txt" -o -name "Pipfile" -o -name "pyproject.toml" \) 2>/dev/null | grep -q .; then
    langs+=("python")
  fi

  [[ -f "$PROJECT_ROOT/pom.xml" ]] && langs+=("java")
  [[ -f "$PROJECT_ROOT/build.gradle" ]] && langs+=("java")
  [[ -f "$PROJECT_ROOT/go.mod" ]] && langs+=("go")
  [[ -f "$PROJECT_ROOT/Gemfile" ]] && langs+=("ruby")
  [[ -f "$PROJECT_ROOT/composer.json" ]] && langs+=("php")

  # Docker
  [[ -f "$PROJECT_ROOT/Dockerfile" ]] && langs+=("docker")

  printf '%s\n' "${langs[@]}" | sort -u
}

# ─── 规则合并 ─────────────────────────────────────────────────────────────────

merge_rules() {
  local target_file="$1"
  shift
  local rule_files=("$@")

  {
    echo "# Auto-generated by scripts/sync-ignore-files.sh"
    echo "# DO NOT EDIT MANUALLY — modify scripts/ignore-rules/*.rules instead"
    echo "# Last updated: $(date -u +%Y-%m-%dT%H:%M:%SZ)"
    echo ""

    for rule_file in "${rule_files[@]}"; do
      if [[ -f "$rule_file" ]]; then
        echo "# ────────────────────────────────────────────────────────────────"
        echo "# $(basename "$rule_file" .rules)"
        echo "# ────────────────────────────────────────────────────────────────"
        cat "$rule_file"
        echo ""
      fi
    done
  } > "$target_file"

  echo "✓ Generated: $target_file"
}

# ─── 主流程 ───────────────────────────────────────────────────────────────────

main() {
  local mode="generate"
  local explicit_langs=()

  while [[ $# -gt 0 ]]; do
    case "$1" in
      --check) mode="check"; shift ;;
      --lang) explicit_langs=(${2//,/ }); shift 2 ;;
      --lang=*) explicit_langs=(${1#*=}); explicit_langs=(${explicit_langs//,/ }); shift ;;
      *) echo "Unknown option: $1" >&2; exit 1 ;;
    esac
  done

  mkdir -p "$RULES_DIR"

  # 检测语言
  local detected_langs=()
  if [[ ${#explicit_langs[@]} -gt 0 ]]; then
    detected_langs=("${explicit_langs[@]}")
  else
    while IFS= read -r lang; do
      detected_langs+=("$lang")
    done < <(detect_languages)
  fi

  echo "Detected languages: ${detected_langs[*]}"

  # 构建规则文件列表（优先级顺序）
  local common_rules=(
    "$RULES_DIR/00-header.rules"
    "$RULES_DIR/10-system.rules"
    "$RULES_DIR/20-ide.rules"
    "$RULES_DIR/30-security.rules"
  )

  local lang_rules=()
  for lang in "${detected_langs[@]}"; do
    lang_rules+=("$RULES_DIR/lang-$lang.rules")
  done

  local project_rules=(
    "$RULES_DIR/90-project-specific.rules"
  )

  # ── .gitignore ──
  local git_rules=("${common_rules[@]}" "${lang_rules[@]}" "$RULES_DIR/git-extra.rules" "${project_rules[@]}")

  if [[ "$mode" == "check" ]]; then
    local temp_git
    temp_git=$(mktemp)
    merge_rules "$temp_git" "${git_rules[@]}" >/dev/null
    if ! diff -q "$PROJECT_ROOT/.gitignore" "$temp_git" >/dev/null 2>&1; then
      echo "❌ .gitignore needs update. Run: bash scripts/sync-ignore-files.sh" >&2
      rm "$temp_git"
      exit 1
    fi
    rm "$temp_git"
    echo "✓ .gitignore is up-to-date"
  else
    merge_rules "$PROJECT_ROOT/.gitignore" "${git_rules[@]}"
  fi

  # ── .dockerignore ──
  if [[ " ${detected_langs[*]} " =~ " docker " ]] || [[ -f "$PROJECT_ROOT/Dockerfile" ]]; then
    local docker_rules=("${common_rules[@]}" "${lang_rules[@]}" "$RULES_DIR/docker-extra.rules")
    merge_rules "$PROJECT_ROOT/.dockerignore" "${docker_rules[@]}"
  fi

  # ── .claudeignore ──
  local claude_rules=("${common_rules[@]}" "${lang_rules[@]}" "$RULES_DIR/claude-extra.rules" "${project_rules[@]}")
  merge_rules "$PROJECT_ROOT/.claudeignore" "${claude_rules[@]}"

  echo ""
  echo "✅ All ignore files synced"
}

main "$@"
