#!/usr/bin/env bash
# sync-ignore-files.sh — 规则驱动的 ignore 文件动态生成器
#
# 用法：
#   bash scripts/sync-ignore-files.sh                    # 检测语言 + 生成所有 ignore 文件
#   bash scripts/sync-ignore-files.sh --check            # 检查是否需要更新（exit 1 if dirty）
#   bash scripts/sync-ignore-files.sh --lang rust,node   # 仅生成指定语言规则
#   bash scripts/sync-ignore-files.sh --use-gitignore-io # 使用 gitignore.io API（需网络）
#
# 原理：
#   1. 扫描项目检测语言（Cargo.toml → rust, package.json → node, etc.）
#   2. 优先级：本地规则（scripts/ignore-rules/*.rules）> gitignore.io API
#   3. 合并生成 .gitignore / .dockerignore / .claudeignore

set -eo pipefail

PROJECT_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
RULES_DIR="$PROJECT_ROOT/scripts/ignore-rules"
USE_GITIGNORE_IO=false

# gitignore.io 语言映射（兼容 bash 3.x）
map_lang_to_gitignore_io() {
  case "$1" in
    node) echo "node" ;;
    rust) echo "rust" ;;
    python) echo "python" ;;
    java) echo "java,maven,gradle" ;;
    go) echo "go" ;;
    ruby) echo "ruby" ;;
    php) echo "php,composer" ;;
    docker) echo "docker" ;;
    *) echo "" ;;
  esac
}

# ─── 语言检测 ─────────────────────────────────────────────────────────────────

detect_languages() {
  local langs=()

  [[ -f "$PROJECT_ROOT/rust/Cargo.toml" ]] && langs+=("rust")
  [[ -f "$PROJECT_ROOT/node/package.json" ]] && langs+=("node")
  [[ -f "$PROJECT_ROOT/package.json" ]] && langs+=("node")

  # Python: setup.py / requirements.txt / Pipfile / pyproject.toml
  if find "$PROJECT_ROOT" -maxdepth 3 -type f \( -name "setup.py" -o -name "requirements.txt" -o -name "Pipfile" -o -name "pyproject.toml" \) 2>/dev/null | grep -q .; then
    langs+=("python")
  fi

  [[ -f "$PROJECT_ROOT/pom.xml" ]] && langs+=("java")
  [[ -f "$PROJECT_ROOT/build.gradle" ]] && langs+=("java")
  [[ -f "$PROJECT_ROOT/go.mod" ]] && langs+=("go")
  [[ -f "$PROJECT_ROOT/Gemfile" ]] && langs+=("ruby")
  [[ -f "$PROJECT_ROOT/composer.json" ]] && langs+=("php")

  # Docker
  [[ -f "$PROJECT_ROOT/Dockerfile" ]] && langs+=("docker")

  printf '%s\n' "${langs[@]}" | sort -u
}

# ─── gitignore.io 集成 ────────────────────────────────────────────────────────

fetch_from_gitignore_io() {
  local langs=("$@")
  local templates=()

  for lang in "${langs[@]}"; do
    local mapped
    mapped=$(map_lang_to_gitignore_io "$lang")
    if [[ -n "$mapped" ]]; then
      templates+=("$mapped")
    fi
  done

  if [[ ${#templates[@]} -eq 0 ]]; then
    echo "# No gitignore.io templates for detected languages" >&2
    return 1
  fi

  local api_query
  api_query=$(IFS=,; echo "${templates[*]}")
  local url="https://www.toptal.com/developers/gitignore/api/$api_query"

  echo "📡 Fetching from gitignore.io: $api_query" >&2

  if command -v curl >/dev/null 2>&1; then
    curl -fsSL "$url" 2>/dev/null || {
      echo "# Failed to fetch from gitignore.io" >&2
      return 1
    }
  else
    echo "# curl not found, cannot fetch from gitignore.io" >&2
    return 1
  fi
}

# ─── 规则合并 ─────────────────────────────────────────────────────────────────

merge_rules() {
  local target_file="$1"
  shift
  local rule_files=("$@")

  {
    echo "# Auto-generated by scripts/sync-ignore-files.sh"
    if [[ "$USE_GITIGNORE_IO" == "true" ]]; then
      echo "# Source: gitignore.io API + local rules"
    else
      echo "# Source: local rules (scripts/ignore-rules/*.rules)"
    fi
    echo "# DO NOT EDIT MANUALLY — modify scripts/ignore-rules/*.rules instead"
    echo "# Last updated: $(date -u +%Y-%m-%dT%H:%M:%SZ)"
    echo ""

    for rule_file in "${rule_files[@]}"; do
      if [[ -f "$rule_file" ]]; then
        echo "# ────────────────────────────────────────────────────────────────"
        echo "# $(basename "$rule_file" .rules)"
        echo "# ────────────────────────────────────────────────────────────────"
        cat "$rule_file"
        echo ""
      fi
    done
  } > "$target_file"

  echo "✓ Generated: $target_file"
}

# ─── 主流程 ───────────────────────────────────────────────────────────────────

main() {
  local mode="generate"
  local explicit_langs=()

  while [[ $# -gt 0 ]]; do
    case "$1" in
      --check) mode="check"; shift ;;
      --lang) explicit_langs=(${2//,/ }); shift 2 ;;
      --lang=*) explicit_langs=(${1#*=}); explicit_langs=(${explicit_langs//,/ }); shift ;;
      --use-gitignore-io) USE_GITIGNORE_IO=true; shift ;;
      *) echo "Unknown option: $1" >&2; exit 1 ;;
    esac
  done

  mkdir -p "$RULES_DIR"

  # 检测语言
  local detected_langs=()
  if [[ ${#explicit_langs[@]} -gt 0 ]]; then
    detected_langs=("${explicit_langs[@]}")
  else
    while IFS= read -r lang; do
      detected_langs+=("$lang")
    done < <(detect_languages)
  fi

  echo "Detected languages: ${detected_langs[*]}"

  # ── 使用 gitignore.io API ──
  if [[ "$USE_GITIGNORE_IO" == "true" ]]; then
    echo "Using gitignore.io API for base templates..."
    local gitignore_io_content
    gitignore_io_content=$(fetch_from_gitignore_io "${detected_langs[@]}")

    if [[ -n "$gitignore_io_content" ]]; then
      # Save to temp file for merging
      local temp_gitignore_io="$RULES_DIR/.gitignore-io-cache.rules"
      echo "$gitignore_io_content" > "$temp_gitignore_io"
      echo "✓ Cached gitignore.io response: $temp_gitignore_io"
    fi
  fi

  # 构建规则文件列表（优先级顺序）
  local common_rules=(
    "$RULES_DIR/00-header.rules"
    "$RULES_DIR/10-system.rules"
    "$RULES_DIR/20-ide.rules"
    "$RULES_DIR/30-security.rules"
  )

  # gitignore.io cache (if enabled and not using local rules)
  if [[ "$USE_GITIGNORE_IO" == "true" ]]; then
    local gitignore_io_cache="$RULES_DIR/.gitignore-io-cache.rules"
    if [[ -f "$gitignore_io_cache" ]]; then
      common_rules+=("$gitignore_io_cache")
    fi
  fi

  local lang_rules=()
  for lang in "${detected_langs[@]}"; do
    local local_rule="$RULES_DIR/lang-$lang.rules"
    if [[ -f "$local_rule" ]]; then
      lang_rules+=("$local_rule")
    elif [[ "$USE_GITIGNORE_IO" != "true" ]]; then
      echo "⚠ Warning: No local rules for $lang, consider --use-gitignore-io" >&2
    fi
  done

  local project_rules=(
    "$RULES_DIR/90-project-specific.rules"
  )

  # ── .gitignore ──
  local git_rules=("${common_rules[@]}" "${lang_rules[@]}" "$RULES_DIR/git-extra.rules" "${project_rules[@]}")

  if [[ "$mode" == "check" ]]; then
    local temp_git
    temp_git=$(mktemp)
    merge_rules "$temp_git" "${git_rules[@]}" >/dev/null
    if ! diff -q "$PROJECT_ROOT/.gitignore" "$temp_git" >/dev/null 2>&1; then
      echo "❌ .gitignore needs update. Run: bash scripts/sync-ignore-files.sh" >&2
      rm "$temp_git"
      exit 1
    fi
    rm "$temp_git"
    echo "✓ .gitignore is up-to-date"
  else
    merge_rules "$PROJECT_ROOT/.gitignore" "${git_rules[@]}"
  fi

  # ── .dockerignore ──
  if [[ " ${detected_langs[*]} " =~ " docker " ]] || [[ -f "$PROJECT_ROOT/Dockerfile" ]]; then
    local docker_rules=("${common_rules[@]}" "${lang_rules[@]}" "$RULES_DIR/docker-extra.rules")
    merge_rules "$PROJECT_ROOT/.dockerignore" "${docker_rules[@]}"
  fi

  # ── .claudeignore ──
  local claude_rules=("${common_rules[@]}" "${lang_rules[@]}" "$RULES_DIR/claude-extra.rules" "${project_rules[@]}")
  merge_rules "$PROJECT_ROOT/.claudeignore" "${claude_rules[@]}"

  echo ""
  echo "✅ All ignore files synced"
}

main "$@"
